### ISSUE TITLE
Customize notification

### ISSUE THREAD

**Issue by ghost** [pikachu987/NotificationView#4]
Hola, quería verificar si la notificación puede eliminar la parte superior donde aparece el nombre de la aplicación.
Mi idea es que se vea como una vista normal.

![Captura de Pantalla 2020-01-05 a la(s) 17 51 31](https://user-images.githubusercontent.com/48538624/71785922-1e8fa200-2fe4-11ea-8c81-85262a97fe92.png)

**Comment by ghost** [comment]
@pikachu987

**Comment by pikachu987** [comment]
'isHeader' is Header Show & Hide Property

<img width="421" alt="스크린샷 2020-01-12 오후 9 04 54" src="https://user-images.githubusercontent.com/16880502/72218558-38e6f400-357f-11ea-8467-0bcbec65db21.png">

You can customize 'appName', 'appIcon' and 'date'.
<img width="423" alt="스크린샷 2020-01-12 오후 9 04 56" src="https://user-images.githubusercontent.com/16880502/72218560-3a182100-357f-11ea-9254-ce8b2153b9b6.png">
