### ISSUE TITLE
Not rounded top corners

### ISSUE THREAD

**Issue by andrey-krukovskiy** [pikachu987/NotificationView#5]
I have created notification with such code
```
                            let notification = NotificationView.default
                            notification.body = NSLocalizedString("Snapshot saved to Photos", comment: "")
                            notification.show()

```
and get such notification view
<img width="641" alt="Снимок экрана 2020-01-23 в 18 36 26" src="https://user-images.githubusercontent.com/834692/72998933-a7de0b80-3e0f-11ea-8283-5e79fdd2761d.png">

**Comment by pikachu987** [comment]
Thank you. Bug fixes.


![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-24 at 18 37 41](https://user-images.githubusercontent.com/16880502/73059349-e7bcf580-3ed8-11ea-8023-899558217819.png)
